import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as T from '../dist/vendor/three.module.js';
import {GLTFLoader} from '../dist/vendor/GLTFLoader.js';
import {createHuman} from '../dist/human.js';
import {createEnvironments} from '../dist/environments.js';
globalThis.ProgressEvent=class {constructor(type,data){Object.assign(this,{type},data);}};
const json=JSON.parse(fs.readFileSync('dist/assets/rhea/human.gltf','utf8'));
for(const b of json.buffers)b.uri='data:application/octet-stream;base64,'+fs.readFileSync('dist/assets/rhea/'+b.uri).toString('base64');
for(const i of json.images)assert(fs.existsSync('dist/assets/rhea/'+i.uri));
json.images=[];json.textures=[];json.materials=json.materials.map(m=>({name:m.name}));
const asset=await new GLTFLoader().parseAsync(JSON.stringify(json),'');
let hits=0;const h=await createHuman(new T.Scene(),()=>hits++,{asset,raw:JSON.parse(fs.readFileSync('dist/assets/motions.json','utf8')),hair:{scene:new T.Group()}},'rhea');
h.setVisible(true);h.setOutfit('ember');for(let i=0;i<600;i++)h.update(1/60,100,false);assert(hits>=3);
h.setDodge(true);let min=Infinity,max=-Infinity;for(let i=0;i<180;i++){h.update(1/60,0,false);min=Math.min(min,h.getPosition().x);max=Math.max(max,h.getPosition().x);}assert(min<-.4&&max>.4);
h.setDodge(false);for(let i=0;i<120;i++)h.update(1/60,0,false);assert(Math.abs(h.getPosition().x)<.001);
h.setDodge(true);for(let i=0;i<120;i++)h.update(1/60,0,true);assert(Math.abs(h.getPosition().x)<.001);
const env=createEnvironments(new T.Scene());env.set('gym');assert(env.groups.gym.visible&&!env.groups.rooftop.visible);env.set('rooftop');assert(!env.groups.gym.visible&&env.groups.rooftop.visible);env.set('classroom');assert(!env.groups.gym.visible&&!env.groups.rooftop.visible);
console.log('PASS: Rhea assets, punches, outfits, dodge recovery, reduced motion and independent environments');
